language: node_js
dist: focal
arch: amd64
cache: npm
os:
  - linux
  - osx
  - windows
node_js:
  - 16
  - 15
  - 14
  - 13
  - 12
install:
  - npm install
script:
  - npm run test
  - npm run build
  - npm run example
